# Generated by Django 5.1.4 on 2026-06-16 20:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_mascota_codigo_qr_alter_mascota_genero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacaQR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=255, unique=True)),
                ('tipo_mascota', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro', 'Otro')], max_length=20)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Asignada', 'Asignada')], default='Disponible', max_length=20)),
                ('fecha_generacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='codigo_qr',
        ),
        migrations.AddField(
            model_name='mascota',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='estado',
            field=models.CharField(default='Activo', max_length=20),
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mascota',
            name='senas_particulares',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='estado',
            field=models.CharField(default='Activo', max_length=20),
        ),
        migrations.AddField(
            model_name='propietario',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Raza o especie'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='placa_qr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mascota', to='empresa.placaqr'),
        ),
        migrations.CreateModel(
            name='ReporteMascotaEncontrada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reporte', models.DateTimeField(default=django.utils.timezone.now)),
                ('medio_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('estado_reporte', models.CharField(default='Pendiente', max_length=30)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='empresa.eventoqr')),
            ],
        ),
    ]
