# Generated by Django 5.1.4 on 2026-06-17 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_propietario_mostrar_contacto_publico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportemascotaencontrada',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reportemascotaencontrada',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reportemascotaencontrada',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes_encontrada', to='empresa.mascota'),
        ),
        migrations.AddField(
            model_name='reportemascotaencontrada',
            name='nombre_reportante',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='reportemascotaencontrada',
            name='referencia_ubicacion',
            field=models.TextField(blank=True, help_text='Referencia manual del lugar donde se encontró la mascota.', null=True),
        ),
        migrations.AddField(
            model_name='reportemascotaencontrada',
            name='telefono_reportante',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reportemascotaencontrada',
            name='estado_reporte',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En seguimiento', 'En seguimiento'), ('Resuelto', 'Resuelto')], default='Pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='reportemascotaencontrada',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='empresa.eventoqr'),
        ),
    ]
